language: ruby
before_install:
  - ./install_bundler.sh
env:
  - RAILS_VERSION=6.1.0
  - RAILS_VERSION=6.0.0
  - RAILS_VERSION=5.2.0
  - RAILS_VERSION=5.1.0
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
matrix:
  include:
    - rvm: 2.5
      env: RAILS_VERSION=4.2
  exclude:
    - rvm: 2.4
      env: RAILS_VERSION=6.0.0
    - rvm: 2.4
      env: RAILS_VERSION=6.1.0
