language: ruby
before_install:
  - ./install_bundler.sh
env:
  - RAILS_VERSION=6.0
  - RAILS_VERSION=5.2
  - RAILS_VERSION=5.1
rvm:
  - 2.4
  - 2.5
  - 2.6
matrix:
  include:
    - rvm: 2.5
      env: RAILS_VERSION=4.2
  exclude:
    - rvm: 2.4
      env: RAILS_VERSION=6.0
